/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swift.upi;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.InetSocketAddress;
import java.net.Socket;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import java.sql.*;
/**
 *
 * @author J.A.R.V.I.S
 */
public class LoginUI extends javax.swing.JFrame {


    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
       detectNetwork();
    }
    
     public void detectNetwork(){
        Thread timer=new Thread(){
            @Override
            public void run(){
                for(;;){
                       Socket socket=new Socket();
                      InetSocketAddress address=new InetSocketAddress("www.db4free.net",80);
                    try{
                      socket.connect(address);
                      x=0;
                    }
                    catch(IOException e)
                {
                   x=1;
                }
                    try{
                        sleep(10);
                    }
                    catch(InterruptedException e)
                {
                    e.printStackTrace();
                }
                }
            }
        };
                timer.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        String name=null,upi=null;
      int x;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Recovery = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRname = new javax.swing.JTextField();
        txtRupi = new javax.swing.JTextField();
        verifyBtn = new javax.swing.JButton();
        cancel1Btn = new javax.swing.JLabel();
        txtRmobile = new javax.swing.JTextField();
        NewPass = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        newRepass = new javax.swing.JPasswordField();
        changeBtn = new javax.swing.JButton();
        ch = new javax.swing.JCheckBox();
        cancel2Btn = new javax.swing.JLabel();
        res = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        createBtn = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        c1 = new javax.swing.JCheckBox();
        loginBtn = new javax.swing.JButton();
        forgetBtn = new javax.swing.JLabel();

        Recovery.setTitle("Account recovery - SWIFT UPI");
        Recovery.setIconImage(new ImageIcon(getClass().getResource("UPI_symbol.png")).getImage());
        Recovery.setMinimumSize(new java.awt.Dimension(464, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(464, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(464, 400));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/Name_Logo.jpg"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/Upi.png"))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Account recovery");

        txtRname.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtRname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter your name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N

        txtRupi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtRupi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter your UPI ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N

        verifyBtn.setBackground(new java.awt.Color(72, 133, 237));
        verifyBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        verifyBtn.setForeground(new java.awt.Color(255, 255, 255));
        verifyBtn.setText("Next");
        verifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });

        cancel1Btn.setBackground(new java.awt.Color(255, 255, 255));
        cancel1Btn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cancel1Btn.setForeground(new java.awt.Color(72, 133, 237));
        cancel1Btn.setText("Cancel");
        cancel1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel1Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel1BtnMouseClicked(evt);
            }
        });

        txtRmobile.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtRmobile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mobile No. (Optional)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtRmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRmobileKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cancel1Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                                .addComponent(verifyBtn))
                            .addComponent(txtRname)
                            .addComponent(txtRupi)
                            .addComponent(txtRmobile)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtRname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtRupi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtRmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyBtn)
                    .addComponent(cancel1Btn))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RecoveryLayout = new javax.swing.GroupLayout(Recovery.getContentPane());
        Recovery.getContentPane().setLayout(RecoveryLayout);
        RecoveryLayout.setHorizontalGroup(
            RecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RecoveryLayout.setVerticalGroup(
            RecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NewPass.setTitle("Account recovery - SWIFT UPI");
        NewPass.setIconImage(new ImageIcon(getClass().getResource("UPI_symbol.png")).getImage());
        NewPass.setMinimumSize(new java.awt.Dimension(470, 400));
        NewPass.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(470, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(470, 400));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/Name_Logo.jpg"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/Upi.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setText("Account recovery");

        newPass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        newPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPassKeyTyped(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Enter your new password");

        newRepass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Re-type password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        newRepass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newRepassKeyTyped(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(72, 133, 237));
        changeBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setText("Change password");
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        ch.setBackground(new java.awt.Color(255, 255, 255));
        ch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ch.setText("Show");
        ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActionPerformed(evt);
            }
        });

        cancel2Btn.setBackground(new java.awt.Color(255, 255, 255));
        cancel2Btn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cancel2Btn.setForeground(new java.awt.Color(72, 133, 237));
        cancel2Btn.setText("Cancel");
        cancel2Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel2BtnMouseClicked(evt);
            }
        });

        res.setBackground(new java.awt.Color(255, 255, 255));
        res.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cancel2Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                .addComponent(changeBtn))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addComponent(jLabel13)
                            .addComponent(newPass)
                            .addComponent(newRepass))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(newRepass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch)
                    .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel2Btn)
                    .addComponent(changeBtn))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout NewPassLayout = new javax.swing.GroupLayout(NewPass.getContentPane());
        NewPass.getContentPane().setLayout(NewPassLayout);
        NewPassLayout.setHorizontalGroup(
            NewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NewPassLayout.setVerticalGroup(
            NewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - SWIFT UPI");
        setIconImage(new ImageIcon(getClass().getResource("UPI_symbol.png")).getImage());
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/Name_Logo.jpg"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/Upi.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sign in");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("with your Swift Account");

        txtUser.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UPI ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N

        createBtn.setBackground(new java.awt.Color(255, 255, 255));
        createBtn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        createBtn.setForeground(new java.awt.Color(72, 133, 237));
        createBtn.setText("Create Account");
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBtnMouseClicked(evt);
            }
        });

        txtPass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter your password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setText("Show Password");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(72, 133, 237));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setPreferredSize(new java.awt.Dimension(90, 34));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        forgetBtn.setBackground(new java.awt.Color(255, 255, 255));
        forgetBtn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        forgetBtn.setForeground(new java.awt.Color(72, 133, 237));
        forgetBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgetBtn.setText("Forgot password ?");
        forgetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forgetBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPass)
                        .addComponent(txtUser)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(c1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(createBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(11, 11, 11))))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(c1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(forgetBtn)
                        .addGap(18, 18, 18)
                        .addComponent(createBtn)))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseClicked
        {new SignUpUI().setVisible(true);
            dispose();
}        // TODO add your handling code here:
    }//GEN-LAST:event_createBtnMouseClicked

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
String pass=new String(txtPass.getPassword());
if(c1.isSelected()){
    c1.setText("Hide Password");
    txtPass.setEchoChar((char)0);
}
else{
    c1.setText("Show Password");
    txtPass.setEchoChar('\u25cf');
}
       
// TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    }//GEN-LAST:event_formKeyPressed

    private void chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActionPerformed
String pass=new String(newPass.getPassword());
String repass=new String(newRepass.getPassword());

if(ch.isSelected()){
           ch.setText("Hide");
           newPass.setEchoChar((char)0);
            newRepass.setEchoChar((char)0);}
else
{   ch.setText("Show");
    newPass.setEchoChar('\u25cf');
    newRepass.setEchoChar('\u25cf');}// TODO add your handling code here:
    }//GEN-LAST:event_chActionPerformed

    private void cancel2BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel2BtnMouseClicked
        this.NewPass.dispose();
        txtRname.setText("");
        txtRupi.setText("");
        txtRmobile.setText("");
        newPass.setText("");
        newRepass.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_cancel2BtnMouseClicked

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
 name=txtRname.getText();
 upi=txtRupi.getText();

 
if(name.equals("") || upi.equals(""))
{
    JOptionPane.showMessageDialog(null,"Please give your name and UPI ID","Information",1);
    if(name.equals(""))
    {
        txtRname.setBorder(BorderFactory.createTitledBorder(null,"Enter your name",TitledBorder.DEFAULT_JUSTIFICATION , TitledBorder.DEFAULT_POSITION,new Font("SansSerif",Font.PLAIN,12), Color.RED));
    }
    if (upi.equals(""))
    {
         txtRname.setBorder(BorderFactory.createTitledBorder(null,"Enter your UPI ID",TitledBorder.DEFAULT_JUSTIFICATION , TitledBorder.DEFAULT_POSITION,new Font("SansSerif",Font.PLAIN,12), Color.RED));
    }
}
else
{   if(x==0){
    try{
        String query="select * from UserDetail where Name=? and Upi_ID=?";
        pst=DbConnect.getConnection().prepareStatement(query);
        pst.setString(1, name);
        pst.setString(2,upi);
        rs=pst.executeQuery();
      if(rs.next())
     {
       this.Recovery.dispose();
       NewPass.setVisible(true);
       NewPass.setLocationRelativeTo(null);
    }
     else
      {
          JOptionPane.showMessageDialog(null,"Name or UPI ID does not exists. Please try again!","Error",0);
                  
      }
            
}
    catch(SQLException | HeadlessException ex)
{
JOptionPane.showMessageDialog(null,ex);
}
}
else{
    JOptionPane.showMessageDialog(null,"Oops! No Internet Connection.");
}
}  
// TODO add your handling code here:
    }//GEN-LAST:event_verifyBtnActionPerformed

    private void cancel1BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1BtnMouseClicked
        this.Recovery.dispose();      
        txtRname.setText("");
txtRupi.setText("");
txtRmobile.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_cancel1BtnMouseClicked

    private void forgetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetBtnMouseClicked
        {Recovery.setVisible(true);
         Recovery.setLocationRelativeTo(null);
         }// TODO add your handling code here:
    }//GEN-LAST:event_forgetBtnMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
     
String ID=txtUser.getText();
String pwd=new String(txtPass.getPassword());


if(ID.equals("") || pwd.equals(""))
{
    JOptionPane.showMessageDialog(null,"All feilds are required.");
    if(ID.equals("")){
         txtUser.setBorder(BorderFactory.createTitledBorder(null,"UPI ID",TitledBorder.DEFAULT_JUSTIFICATION , TitledBorder.DEFAULT_POSITION,new Font("Tahoma",Font.PLAIN,11), Color.RED));
    }
    if(pwd.equals("")){
        txtPass.setBorder(BorderFactory.createTitledBorder(null, "Enter your password", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Tahoma",Font.PLAIN,11), Color.RED));
    }
}

else
{  if(x==0){
try{
String sql="select * from UserDetail where Upi_ID=? and password=?";
pst=DbConnect.getConnection().prepareStatement(sql);
pst.setString(1,ID);
pst.setString(2,pwd);
rs=pst.executeQuery();
if(rs.next())
{
String nm= rs.getString("Name");  
long mobile=rs.getLong("Mobile");
String upiID=rs.getString("Upi_ID");
String virt=rs.getString("Virtual_ID");
int n=nm.length();
int w=(int) ((n*8.74)+40);

HomeScreenUI home=new HomeScreenUI();
home.txtUname.setSize(w, 35);
home.txtUname.setText(" Welcome, "+nm);
home.txtPname.setText(nm);
home.txtPmobile.setText(""+mobile);
home.txtPupi.setText(upiID);
home.txtVirtID.setText(virt);
 home.setVisible(true);
 dispose();
}
else
{
JOptionPane.showMessageDialog(null, "Incorrect UPI ID or password. Please try again!","Access Denied!",0);
}
}
catch(SQLException | HeadlessException ex)
{
JOptionPane.showMessageDialog(null,ex);
} } 
else
{
    JOptionPane.showMessageDialog(null,"Oops! No Internet Connection.");
}
}
    }//GEN-LAST:event_loginBtnActionPerformed

    private void newRepassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newRepassKeyTyped
String pass=new String(newPass.getPassword());
if(pass.length()>=20)
{evt.consume();
     } 
        
String rePass=new String(newRepass.getPassword());
        if(pass.equals(rePass)){
            res.setText("Matched");
            res.setForeground(Color.GREEN);
        }
        else  if(!pass.equals(rePass))
        {
            res.setText("Not Matched");
            res.setForeground(Color.RED);
        }
        else if(rePass.length()<=0){
            res.setText("");}        // TODO add your handling code here:
    }//GEN-LAST:event_newRepassKeyTyped

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
String pas=new String(newPass.getPassword());
String rePass=new String(newRepass.getPassword());
name=txtRname.getText();
upi=txtRupi.getText();

if(x==0){
try{
    String query1="Update UserDetail set password=? , rePassword=? where Name=? And Upi_ID=?;";
    pst=DbConnect.getConnection().prepareStatement(query1);
    pst.setString(1,pas);
    pst.setString(2,rePass);
    pst.setString(3,name);
    pst.setString(4,upi);
    
    int rs=pst.executeUpdate();
    if(rs>0){
        JOptionPane.showMessageDialog(null,"Password changed successfully","Successful!",1);
        this.NewPass.dispose();
        txtRname.setText("");
        txtRupi.setText("");
        txtRmobile.setText("");
        newPass.setText("");
        newRepass.setText("");
        
    }
    else{
        JOptionPane.showMessageDialog(null,"Unable to change password. Please try again!","Error",0);
        txtRname.setText("");
        txtRupi.setText("");
        txtRmobile.setText("");
        newPass.setText("");
        newRepass.setText("");
    }
}
catch(SQLException | HeadlessException ex)
{
   JOptionPane.showMessageDialog(null,ex);
}  
}
else{
    JOptionPane.showMessageDialog(null,"Oops! No Internet Connection.");
}
    }//GEN-LAST:event_changeBtnActionPerformed

    private void newPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPassKeyTyped
String pass=new String(newPass.getPassword());
if(pass.length()>=20)
{evt.consume();
     } 
// TODO add your handling code here:
    }//GEN-LAST:event_newPassKeyTyped

    private void txtRmobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRmobileKeyTyped
char enter=evt.getKeyChar();
if(!(Character.isDigit(enter)))
{evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_txtRmobileKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog NewPass;
    private javax.swing.JDialog Recovery;
    private javax.swing.JCheckBox c1;
    private javax.swing.JLabel cancel1Btn;
    private javax.swing.JLabel cancel2Btn;
    private javax.swing.JCheckBox ch;
    private javax.swing.JButton changeBtn;
    private javax.swing.JLabel createBtn;
    private javax.swing.JLabel forgetBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField newRepass;
    private javax.swing.JLabel res;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtRmobile;
    private javax.swing.JTextField txtRname;
    private javax.swing.JTextField txtRupi;
    public javax.swing.JTextField txtUser;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
