/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swift.upi;

import java.awt.Color;
import java.awt.HeadlessException;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author J.A.R.V.I.S
 */
public class SignUpUI extends javax.swing.JFrame {

    /**
     * Creates new form SignUpUI
     */
    public SignUpUI() {
        initComponents();
        detectNetwork();
    }

     public void detectNetwork(){
        Thread timer=new Thread(){
            @Override
            public void run(){
                for(;;){
                       Socket socket=new Socket();
                      InetSocketAddress address=new InetSocketAddress("www.db4free.net",80);
                    try{
                      socket.connect(address);
                      x=0;
                    }
                    catch(IOException e)
                {
                   x=1;
                }
                    try{
                        sleep(10);
                    }
                    catch(InterruptedException e)
                {
                    e.printStackTrace();
                }
                }
            }
        };
                timer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    int x;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        txtAcc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        signInBtn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtRepass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        conf = new javax.swing.JLabel();
        rs = new javax.swing.JLabel();
        signupBtn = new javax.swing.JButton();
        txtBank = new javax.swing.JComboBox<>();
        txtPin = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtRePin = new javax.swing.JPasswordField();
        res = new javax.swing.JLabel();
        c2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up - SWIFT UPI");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new ImageIcon(getClass().getResource("UPI_symbol.png")).getImage());
        setMinimumSize(new java.awt.Dimension(672, 700));
        setPreferredSize(new java.awt.Dimension(672, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(672, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/Name_Logo.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setText("Create your Swift Account");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UPI ID *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("You can use letters, numbers & symbols ");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Use 8 or more characters with a mix of letters, numbers & symbols");

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setText("Show");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        txtAcc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAcc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account No. *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtAcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccKeyTyped(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("We'll use your number for account security. It \nwon't be visible to others.");

        txtMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMobile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mobile No. *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileKeyTyped(evt);
            }
        });

        signInBtn.setBackground(new java.awt.Color(255, 255, 255));
        signInBtn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        signInBtn.setForeground(new java.awt.Color(72, 133, 237));
        signInBtn.setText("Sign in instead");
        signInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInBtnMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/SecurityPic.png"))); // NOI18N

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        txtRepass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRepass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Re-type Password *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtRepass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRepassKeyTyped(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swift/upi/Upi.png"))); // NOI18N

        conf.setBackground(new java.awt.Color(255, 255, 255));
        conf.setPreferredSize(new java.awt.Dimension(40, 14));

        rs.setBackground(new java.awt.Color(255, 255, 255));
        rs.setPreferredSize(new java.awt.Dimension(40, 14));

        signupBtn.setBackground(new java.awt.Color(72, 133, 237));
        signupBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Sign Up");
        signupBtn.setPreferredSize(new java.awt.Dimension(94, 36));
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        txtBank.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Bank--", "State Bank Of India", "HDFC Bank", "ICICI Bank", "Punjab National Bank", "Axis Bank", "Canara Bank", "Bank of Baroda", "Union Bank", "IDBI Bank", "Bank of India" }));
        txtBank.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Bank *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N

        txtPin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UPI PIN 6-digit *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPinKeyTyped(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("* Required Feilds");

        txtRePin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRePin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Re-type UPI PIN *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(72, 133, 237))); // NOI18N
        txtRePin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRePinKeyTyped(evt);
            }
        });

        res.setBackground(new java.awt.Color(255, 255, 255));
        res.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        c2.setText("Show");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("eg: 123456@upi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRepass, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(rs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(conf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(c1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(txtAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtRePin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(c2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(signInBtn)
                .addGap(256, 256, 256)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(txtRepass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(conf, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(c1)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRePin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(c2)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(signInBtn))
                    .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRepassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepassKeyTyped
        String pass=new String(txtPass.getPassword());
        String rePass=new String(txtRepass.getPassword());
        if(pass.equals(rePass)){
            conf.setText("Matched");
            conf.setForeground(Color.GREEN);
        }
        else  if(!pass.equals(rePass))
        {
            conf.setText("Not Matched");
            conf.setForeground(Color.RED);
        }
        else if(pass.length()<=0){
            conf.setText("");}
    }//GEN-LAST:event_txtRepassKeyTyped

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        rs.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassFocusLost

    private void signInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseClicked
        {new LoginUI().setVisible(true);
            dispose();}        // TODO add your handling code here:
    }//GEN-LAST:event_signInBtnMouseClicked

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        
        if(c1.isSelected()){
            c1.setText("Hide");
            txtPass.setEchoChar((char)0);
            txtRepass.setEchoChar((char)0);
        }
        else{
            c1.setText("Show");
            txtPass.setEchoChar('\u25cf');
            txtRepass.setEchoChar('\u25cf');

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed

String name=txtName.getText();
String id=txtID.getText();
String pass=new String(txtPass.getPassword());
String rePass=new String(txtRepass.getPassword());
String bank=(String) txtBank.getSelectedItem();
long acc=Long.parseLong(txtAcc.getText());
long mobile=Long.parseLong(txtMobile.getText());
String pin=new String(txtPin.getPassword());
String rePin=new String(txtRePin.getPassword());

String Mob=txtMobile.getText();
String Acc=txtAcc.getText();

float bal=(float) Math.random() * 1000000;
String AccType="Saving";

if(name.equals("") || id.equals("") || pass.equals("") || rePass.equals("") || txtBank.getSelectedIndex()==0 || Acc.equals("") || Mob.equals("") || pin.equals("") || rePin.equals(""))
{
    JOptionPane.showMessageDialog(null,"All feilds are required.","Information",1);
}

else
  { if(x==0){
    try{
     String query="Select * from UserDetail where Upi_Id=? || Mobile=?;";
     PreparedStatement pst=DbConnect.getConnection().prepareStatement(query);
     pst.setString(1, id);
     pst.setLong(2,mobile);
     ResultSet rs=pst.executeQuery();
     
     String query0="Select * from BankDetail where Account_No=?;";
     PreparedStatement pst0=DbConnect.getConnection().prepareStatement(query0);
     pst0.setLong(1, acc);
     ResultSet r=pst0.executeQuery();
     
     if(rs.next()){
         String ID=rs.getString("Upi_Id");
         String mob=rs.getString("Mobile");
         if(ID.equals(id) && mob.equals(Mob))
         {
           JOptionPane.showMessageDialog(null,"Given UPI ID and Mobile number already exists, Please choose another one","Error",0);  
         }
        if(r.next()){
         String ac=r.getString("Account_No");
         if(ac.equals(Acc))
         {
             JOptionPane.showMessageDialog(null,"This Account number already exists, Please choose another one.","Error",0);
         }
           }
        if(!(ID.equals(id) && mob.equals(Mob)) && ID.equals(id)){
             JOptionPane.showMessageDialog(null,"This UPI ID already exists, Please choose another one.","Error",0);
         }
        if(!(ID.equals(id) && mob.equals(Mob)) && mob.equals(Mob)){
             JOptionPane.showMessageDialog(null,"This Phone number is already registered with another account, please choose another.","Error",0);
         }
        
     }
  else if(r.next()){
         String ac=r.getString("Account_No");
         if(ac.equals(Acc))
         {
             JOptionPane.showMessageDialog(null,"This Account number already exists, Please choose another one.","Error",0);
         }
     }  
     
     
    
else{
    try{
         String query1="Insert into UserDetail(Name,Upi_Id,Password,rePassword,Mobile) values(?,?,?,?,?);";
         PreparedStatement pst1=DbConnect.getConnection().prepareStatement(query1);
         pst1.setString(1,name);
         pst1.setString(2,id);
         pst1.setString(3,pass);
         pst1.setString(4,rePass);
         pst1.setLong(5,mobile);
         
         int n1=pst1.executeUpdate();
         
         String query2="Insert into BankDetail(Upi_ID,Bank,Account_No,Account_Type,Balance,Mobile,Pin,rePin) values(?,?,?,?,?,?,?,?);";
         PreparedStatement pst2=DbConnect.getConnection().prepareStatement(query2);
         pst2.setString(1, id);
         pst2.setString(2, bank);
         pst2.setLong(3, acc);
         pst2.setString(4, AccType);
         pst2.setFloat(5, bal);
         pst2.setLong(6, mobile);
         pst2.setString(7, pin);
         pst2.setString(8,rePin);
         
        int n2=pst2.executeUpdate();
        
        if(n1>0 && n2>0){
            JOptionPane.showMessageDialog(null,"Account created successfully. Please Login","Successful!",1);
            LoginUI frame=new LoginUI();
            frame.txtUser.setText(id);
             dispose();
            frame.setVisible(true);
            
        }
        else 
        {
            JOptionPane.showMessageDialog(null,"Failed to create account. Try agsin!","Error",0);
        }
    }
catch(SQLException | HeadlessException ex)
{
JOptionPane.showMessageDialog(null,ex);
}
    }
    }
    
  catch(SQLException | HeadlessException ex)
{
    JOptionPane.showMessageDialog(null,ex);
            }
    
  }
  else{
      JOptionPane.showMessageDialog(null,"Oops! No Internet Connection.");
  }}
    }//GEN-LAST:event_signupBtnActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
   String pin=new String(txtPin.getPassword());
        String repin=new String(txtRePin.getPassword());

        if(c2.isSelected()){
            c2.setText("Hide");
            txtPin.setEchoChar((char)0);
            txtRePin.setEchoChar((char)0);
        }
        else{
            c2.setText("Show");
            txtPin.setEchoChar('\u25cf');
            txtRePin.setEchoChar('\u25cf');

        }       // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void txtRePinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRePinKeyTyped
 char enter=evt.getKeyChar();
if(!(Character.isDigit(enter)))
{evt.consume();}
        String pin=new String(txtPin.getPassword());
        String rePin=new String(txtRePin.getPassword());
        if(pin.equals(rePin)){
            res.setText("Matched");
            res.setForeground(Color.GREEN);
        }
        else  if(!pin.equals(rePin))
        {
            res.setText("Not Matched");
            res.setForeground(Color.RED);
        }
        else if(rePin.length()<=0){
            res.setText("");}   
 // TODO add your handling code here:
    }//GEN-LAST:event_txtRePinKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
  String pass =new String(txtPass.getPassword());
if(pass.length()>=20)
{evt.consume();
     } 
  
if(pass.length()>=8)
{
rs.setText("Strong");
rs.setForeground(Color.GREEN);
              }
else  if(pass.length()<8)
{
rs.setText("Weak");
rs.setForeground(Color.RED);
}
else if(rs.equals(""))
{
       rs.setText(""); 
   }// TODO add your handling code here:
    }//GEN-LAST:event_txtPassKeyTyped

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
if(txtName.getText().length()>=100)
{evt.consume();    }    // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
if(txtID.getText().length()>=20)
{evt.consume();    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtAccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccKeyTyped
if(txtAcc.getText().length()>=16)
{evt.consume();
      }   
char enter=evt.getKeyChar();
if(!(Character.isDigit(enter)))
{evt.consume();}// TODO add your handling code here:
    }//GEN-LAST:event_txtAccKeyTyped

    private void txtMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyTyped
if(txtMobile.getText().length()>=10)
{evt.consume();
      }
char enter=evt.getKeyChar();
if(!(Character.isDigit(enter)))
{evt.consume();}// TODO add your handling code here:
    }//GEN-LAST:event_txtMobileKeyTyped

    private void txtPinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinKeyTyped
String pass=new String(txtPin.getPassword());
if(pass.length()>=6)
{evt.consume();
     }  
char enter=evt.getKeyChar();
if(!(Character.isDigit(enter)))
{evt.consume();}// TODO add your handling code here:
    }//GEN-LAST:event_txtPinKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JLabel conf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel res;
    private javax.swing.JLabel rs;
    private javax.swing.JLabel signInBtn;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JComboBox<String> txtBank;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPin;
    private javax.swing.JPasswordField txtRePin;
    private javax.swing.JPasswordField txtRepass;
    // End of variables declaration//GEN-END:variables
}
